name: Lint, Security Scan, and Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-scan:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit black pytest

    - name: Run Flake8 (Linting)
      run: |
        flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 scripts/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Run Black (Formatting Check)
      run: black --check scripts/

    - name: Run Security Scan (Bandit)
      run: bandit -r scripts/

    - name: Run Pytest (Test Coverage)
      run: pytest --cov=.
