
paths:
  /user/codespaces:
    get:
      summary: List Codespaces for the authenticated user
      operationId: listUserCodespaces
      responses:
        '200':
          description: A list of codespaces for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodespaceList'
    post:
      summary: Create a new Codespace for the user
      operationId: createUserCodespace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCodespaceRequest'
components:
  schemas:
    CodespaceList:
      type: object
      properties:
        total_count:
          type: integer
        codespaces:
        type: array
        items: 
          $ref: #/components/schemas/Codespace
    Codespace:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        state:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        machine:
          type: string