
openapi: 3.2.0
info:
  title: GitHub API
  version: 1.0.0
paths:
  /user/repos:
    get:
      summary: List repositories for the authenticated user
      operationId: listUserRepositories
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                $ref: '#/components/repositoryList'
components:
  schemas:
    RepositoryList:
      type: object
      properties:
        total_count:
          type: integer
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/Repository'
    Repository:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        private:
          type: boolean
