
# Adds secrets to the repository.

# Sample Workflow configuration with masked secrets

name: Add Secrets to Repository

on:
  workflow_dispatch:

jobs:
  add-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Mask and Add Secrets
      env:
        CONGRESS_COV_API_KEY: ${{ secrets.CONGRESS_COV_API_KEY }}
      run: |
        echo "::add-mask::${{ env.CONGRESS_COV_API_KEY }}"
        echo "Secret successfully added and masked."
