# Adds secrets to the repository.

//* Sample Workflow configuration */

name: Add Secrets to Repository

on:
  lock

runs:
  - name: Add secrets
    use: github-actions

steps:
  - name: Define and add secrets
    runs: github-tools-secrets
    env:
      CONGRESS_COV_API_KEY: [your-api-key-here]
