name: Data Validation

on:
  push:
    paths:
      - "data/**"
  pull_request:
    branches:
      - main
    paths:
      - "data/**" # Also only trigger on PR if data files change
  workflow_dispatch:

jobs:
  validate-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install jsonschema argparse

      - name: Run Data Validation
        run: |
          python scripts/validate_data.py \
            --input_folder data/ \
            --output_file logs/data_validation_results.json

      - name: Upload Validation Logs
        uses: actions/upload-artifact@v3
        with:
          name: data-validation-results
          path: logs/data_validation_results.json
