name: Debug Workflow

on:
  workflow_dispatch:

jobs: 
  debug:
    runs-on: ubuntu-latest
    steps: 
      - name: Start Workflow
        run: echo "Starting Debug Workflow..."

      - name: Print Environment Variables
        run: env

      - name: Print Event Payload
        run: cat $GITHUBE_EVENT_PATH

      - name: Print Debug Message
        run: echo "Workflow is functioning as expected!"
