name: Debug Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  debug:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Debug Message
        run: echo "Hello, the workflow is functioning!"
