# GitHub Actions Workflow

# Workflow to handle failed jobs and provide detailed logs.
onengi:saved-log
name: "Failed Workflow Logs"

git:
commit_types: ["start_point"]

all :
  strigger:
    workflow_dispatch
schedule:
    - name: Mobile Trigger
      user: Matter
      commands:
      - mark Matter: The start point has arrived!
      tools: trigger