
name: Fetch Federal Register Data

on:
  schedule:
    - cron: "0 12 * * *"  # Run daily at 12:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Executive Orders
        run: |
          mkdir -p data  # Ensure the data folder exists
          python scripts/fetch_federal_register_data.py

      - name: Commit and Push Results
        run: |
          if [ "$(ls -A data)" ]; then
            git config user.name "GitHub Action"
            git config user.email "actions@github.com"
            git add data/*
            git commit -m "Update executive orders data"
            git push
          else
            echo "No data files to commit."
