name: Fetch Regulations.gov Data

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 5 AM UTC
  workflow_dispatch: # Allows manual triggering

env:
  REGULATIONS_API_KEY: ${{ secrets.REGULATIONS_API_KEY }}

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push commits

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Cache pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Ensure requests and python-dotenv are installed for fetch_regulations.py
        pip install requests python-dotenv

    - name: Fetch sample Documents from Regulations.gov
      run: |
        python scripts/fetch_regulations.py documents --search-term "climate change" --page-size 5

    - name: Fetch sample Document Details from Regulations.gov
      run: |
        python scripts/fetch_regulations.py document --document-id EPA-HQ-OAR-2021-0295-0001

    - name: Fetch sample Dockets from Regulations.gov
      run: |
        python scripts/fetch_regulations.py dockets --search-term "technology" --page-size 5

    - name: Fetch sample Docket Details from Regulations.gov
      run: |
        python scripts/fetch_regulations.py docket --docket-id EPA-HQ-OAR-2021-0295

    - name: Fetch sample Comments from Regulations.gov
      run: |
        python scripts/fetch_regulations.py comments --search-term "public input" --page-size 5
    
    - name: Fetch sample Comment Details from Regulations.gov
      run: |
        python scripts/fetch_regulations.py comment --comment-id EPA-HQ-OAR-2021-0295-0002

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # Stage any changes in the data/regulations directory
        git add data/regulations/**/*.json # Add all json files in data/regulations and its subdirectories
        # Check if there are staged changes
        if ! git diff --cached --quiet; then
          git commit -m "Automated update of Regulations.gov data"
          git push
        else
          echo "No changes to Regulations.gov data files to commit."
        fi
