name: Test and Lint

on:
  workflow_dispatch

jobs:
  run:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If coverage and pytest are in requirements-dev.txt, install it:
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Or ensure coverage is installed directly
          pip install coverage 
      - name: Lint scripts
        run: flake8 --config .flake8 .
      - name: Run tests with coverage
        run: coverage run -m unittest discover
      - name: Coverage report
        run: coverage report --fail-under=80
