name: Test and Lint

on:
  workflow_dispatch

jobs:
  run:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint scripts
        run: flake8 . --config=.flake8 
      - name: Run tests
        run: python -m unittest discover
