name: Test and Lint

on:
  push
  workflow_dispatch:

runs: 
  - name: Run tests and lint
    run: python:3.10

steps:
  - name: Install dependencies
    run: pip install -r spcip
  - name: Lnt scripts
    run: flake8 scripts/  
  - name: Run tests
    run: python -m unittest.discover
